spring.application.name=hotel-phoenix-backend

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Roshan
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Configuration
server.port=8081

# JWT Configuration (for future use)
app.jwt.secret=5U9r7sR2xH8q4bN6uW1zC0vP3yL5mK8jA7dF4gT9cE=
app.jwt.expiration-ms=86400000
